#!/bin/bash

BIN=$NBITES_DIR/build/nbtool
CROSS=$NBITES_DIR/src/nbcross
BEHAVIORS=$NBITES_DIR/src/man/behaviors
SIM=$NBITES_DIR/src/nbtool/src/behavior_sim
PYTHON=$NBITES_DIR/build/nbcross/install/lib/python

rm -rf $BIN
#might need to make build dir too on some systems
mkdir $BIN

find ./src -name *.java > _tempFiles
javac -d $BIN @_tempFiles

rm _tempFiles

mkdir -p $PYTHON
cd $PYTHON
rm -Rf *
cp $BEHAVIORS/*.py .
cp -r $BEHAVIORS/headTracker .
cp -r $BEHAVIORS/kickDecider .
cp -r $BEHAVIORS/navigator .
cp -r $BEHAVIORS/players .
cp -r $BEHAVIORS/robots .
cp -r $BEHAVIORS/typeDefs .
cp -r $BEHAVIORS/util .
cp $SIM/Switch.py $PYTHON/players

cd $CROSS
make nbcross -j4 &

cd $BIN
java -ea behavior_sim.Gui